backend:
  name: github
  repo: ozluy/destan-nakliyat-gatsby
  branch: master
media_folder: static/assets
public_folder: /assets
site_url: https://destan-nakliyat.netlify.app
collections:
  - name: blog
    label: Blog
    folder: backend/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: faq
    label: Frequently Asked Questions
    folder: backend/faq
    create: true
    widget: list
    allow_add: true
    summary: '{{fields.question}} {{fields.answer}}'
    fields:
      - { name: question, label: Question, widget: text }
      - { name: answer, label: Answer, widget: text }
  - name: sss
    label: Frequently Asked Questions
    folder: backend/sss
    create: true
    widget: list
    allow_add: true
    fields:
      - { name: questions, label: Questions, widget: list }
      - { name: answers, label: Answers, widget: list }